### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by agungsugiarto** [lloricode/lumen-boilerplate#12]
Why do need spatie/laravel-permission instead of using built in feature laravel/passport like scope for authorization ?

Example from docs laravel passport
```php
Route::get('/orders', function () {
    // Access token has both "check-status" and "place-orders" scopes... 
})->middleware(['auth:api', 'scopes:check-status,place-orders']);
```

**Comment by lloricode** [comment]
We need to check this as per user, not per application, some users has limited access on specific resource
