### ISSUE TITLE
 Call to undefined function app_path()

### ISSUE THREAD

**Issue by milanbeo** [lloricode/lumen-boilerplate#14]
It constantly appears in the log file:

```
Uncaught Error: Call to undefined function app_path()
in Command line code:1
```

I tried a solution from ( https://stackoverflow.com/questions/61882276/how-to-call-app-path-function-in-laravel-lumen), but without success.

**Comment by lloricode** [comment]
can you give a procedure how to reproduce that?

**Comment by milanbeo** [comment]
After updating Wamp server and xdebug extensin error gone.
