### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by agungsugiarto** [lloricode/lumen-boilerplate#4]
Hello this project is awesome, can you share template collection for postman. Thanks!

**Comment by agungsugiarto** [comment]
What im missing ?
![image](https://user-images.githubusercontent.com/10989147/69903929-bfca7d80-13d2-11ea-9c92-6bbd9aa15a1d.png)

**Comment by lloricode** [comment]
Thanks, i will push the file later

**Comment by lloricode** [comment]
Hi @agungsugiarto, 

you can now check this publish postman [here](https://documenter.getpostman.com/view/4366674/SWEDzudy)

**Comment by agungsugiarto** [comment]
@lloricode thank you
